version: "2"

services:
  application:
    image: ${DOCKER_NAMESPACE}/${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG}
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    networks:
      - staging-network
    environment:
      - APPLICATION_UID=${APPLICATION_UID}
      - APPLICATION_GID=${APPLICATION_GID}
      - PHP_POST_MAX_SIZE=${PHP_POST_MAX_SIZE}
      - PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE}
      - SERVICE_NGINX_CLIENT_MAX_BODY_SIZE=${SERVICE_NGINX_CLIENT_MAX_BODY_SIZE}
      - WEB_DOCUMENT_ROOT=${WEB_DOCUMENT_ROOT}
      - WEB_ALIAS_DOMAIN=${WEB_ALIAS_DOMAIN}
    volumes:
      - "${PROJECT_APP_DIR}:${CONTAINER_WEB_APP_DIR}"
      - "../config/supervisor/worker.conf:/opt/docker/etc/supervisor.d/worker.conf:ro"
    labels:
      - "traefik.enable=true"
      - "traefil.docker.network=staging-network"
      - "traefik.http.routers.project-app.entrypoints=websecure"
      - "traefik.http.routers.project-app.rule=Host(`${WEB_ALIAS_DOMAIN}`)"

networks:
  staging-network:
    driver: bridge
    external: true
